create database shoppingdb;
use shoppingdb;


create table customers(
customer_id int primary key,
customer_name varchar (50),
city varchar (50)
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(50),
    category VARCHAR(50),
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    quantity INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO customers VALUES
(101, 'Rahul Sharma', 'Nagpur'),
(102, 'Priya Verma', 'Pune'),
(103, 'Amit Patil', 'Mumbai'),
(104, 'Sneha Joshi', 'Nashik');

INSERT INTO products VALUES
(201, 'Laptop', 'Electronics', 55000),
(202, 'Keyboard', 'Accessories', 1500),
(203,'Headphones','Accessories',2500),
(204,'Monitor','Electronics',1200);

INSERT INTO orders VALUES
(10001,101,201,1,'2026-09-01'),(1002,102,203,2,'2026-09-03'),(1003,103,204,1,'2026-09-05'),(1004,101,202,2,'2026-09-07'),(1005,104,203,1,'2026-09-10');

SELECT 
    C.CITY,
    C.CUSTOMER_ID,
    SUM(P.PRICE) AS TOTAL_PRICE
FROM CUSTOMERS C
INNER JOIN ORDERS O 
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P 
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE C.CITY IN ('NAGPUR','PUNE','MUMBAI','NASHIK')
GROUP BY C.CITY, C.CUSTOMER_ID ORDER BY SUM(P.PRICE) DESC;

-- TOP 2 CITY PURCHASE WISE --
SELECT 
    C.CITY,
    C.CUSTOMER_ID,
    SUM(P.PRICE) AS TOTAL_PRICE
FROM CUSTOMERS C
INNER JOIN ORDERS O 
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P 
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE C.CITY IN ('NAGPUR','PUNE','MUMBAI','NASHIK')
GROUP BY C.CITY, C.CUSTOMER_ID ORDER BY SUM(P.PRICE) DESC LIMIT 2;

-- LAST 2 CITY PURCHASE WISE --
SELECT 
    C.CITY,
    C.CUSTOMER_ID,
    SUM(P.PRICE) AS TOTAL_PRICE
FROM CUSTOMERS C
INNER JOIN ORDERS O 
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P 
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE C.CITY IN ('NAGPUR','PUNE','MUMBAI','NASHIK')
GROUP BY C.CITY, C.CUSTOMER_ID ORDER BY SUM(P.PRICE) ASC LIMIT 2;


SELECT 
    P.CATEGORY,DAYNAME(O.ORDER_DATE)AS ORDER_DATE,
    SUM(P.PRICE) AS TOTAL_PRICE,
    C.CITY
FROM CUSTOMERS C
INNER JOIN ORDERS O 
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P 
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 
 DAYNAME(O.ORDER_DATE),CITY,P.CATEGORY
ORDER BY 
SUM(P.PRICE) DESC;


SELECT 
    C.CUSTOMER_ID,COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS
FROM CUSTOMERS C
INNER JOIN ORDERS O 
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P 
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 
C.CUSTOMER_ID
HAVING COUNT(O.ORDER_ID)>1
ORDER BY 
COUNT(O.ORDER_ID) DESC;

